let strip = neopixel.create(DigitalPin.P12, 8, NeoPixelMode.RGB)
basic.forever(function () {
    for (let index = 0; index <= 8; index++) {
        strip.setPixelColor(index, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor((index + 1) % 8, neopixel.colors(NeoPixelColors.Orange))
        strip.setPixelColor((index + 2) % 8, neopixel.colors(NeoPixelColors.Yellow))
        strip.setPixelColor((index + 3) % 8, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor((index + 4) % 8, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor((index + 5) % 8, neopixel.colors(NeoPixelColors.Indigo))
        strip.setPixelColor((index + 6) % 8, neopixel.colors(NeoPixelColors.Purple))
        strip.setPixelColor((index + 7) % 8, neopixel.colors(NeoPixelColors.White))
        strip.show()
        mooncar.MoonCarGo(mooncar.Direction.direct4, 30)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct5, 0)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct3, 30)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct5, 0)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct1, 30)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct5, 0)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct2, 30)
        basic.pause(1000)
        mooncar.MoonCarGo(mooncar.Direction.direct5, 0)
        basic.pause(1000)
    }
})
